const DEMO_OWNERS = [
  { name: 'Marina Alves', handle: '@marina.recomeca', avatarUrl: '/demo/avatars/avatar-01.png', avatarColor: '#d87932' },
  { name: 'Clara Mendes', handle: '@clara.em.movimento', avatarUrl: '/demo/avatars/avatar-02.png', avatarColor: '#bd5b52' },
  { name: 'Kenji Sato', handle: '@kenji.ritmo', avatarUrl: '/demo/avatars/avatar-03.png', avatarColor: '#4f6b8a' },
  { name: 'Lina Torres', handle: '@lina.passoapasso', avatarUrl: '/demo/avatars/avatar-04.png', avatarColor: '#687d5f' },
  { name: 'Paulo Neri', handle: '@paulo.reconstroi', avatarUrl: '/demo/avatars/avatar-05.png', avatarColor: '#5d6c57' },
  { name: 'Zuri Coleman', handle: '@zuri.draws.again', avatarUrl: '/demo/avatars/avatar-06.png', avatarColor: '#4a7d91' },
  { name: 'Nicolas Hart', handle: '@nick.trying', avatarUrl: '/demo/avatars/avatar-07.png', avatarColor: '#866a52' },
  { name: 'Helena Duarte', handle: '@helena.calma', avatarUrl: '/demo/avatars/avatar-08.png', avatarColor: '#9a7b5d' },
  { name: 'Mei Lin', handle: '@mei.mornings', avatarUrl: '/demo/avatars/avatar-09.png', avatarColor: '#7b8f87' },
  { name: 'Diego Costa', handle: '@diego.umdia', avatarUrl: '/demo/avatars/avatar-10.png', avatarColor: '#c57a43' },
  { name: 'Laura Vidal', handle: '@laura.em.casa', avatarUrl: '/demo/avatars/avatar-11.png', avatarColor: '#6f8365' },
  { name: 'Omar Rahman', handle: '@omar.reading', avatarUrl: '/demo/avatars/avatar-12.png', avatarColor: '#506d8a' },
  { name: 'Sofia Reis', handle: '@sofia.sempressa', avatarUrl: '/demo/avatars/avatar-13.png', avatarColor: '#c26a4a' },
  { name: 'Yuri Tanaka', handle: '@yuri.noiteprodutiva', avatarUrl: '/demo/avatars/avatar-14.png', avatarColor: '#60748c' },
  { name: 'Amira Said', handle: '@amira.returns', avatarUrl: '/demo/avatars/avatar-15.png', avatarColor: '#c88054' },
  { name: 'Leo Martins', handle: '@leo.building', avatarUrl: '/demo/avatars/avatar-16.png', avatarColor: '#728f7a' },
  { name: 'Ines Romero', handle: '@ines.recomeco', avatarUrl: '/demo/avatars/avatar-17.png', avatarColor: '#866b60' },
  { name: 'Bruno Araujo', handle: '@bruno.codepath', avatarUrl: '/demo/avatars/avatar-18.png', avatarColor: '#b56644' },
  { name: 'Ada Brooks', handle: '@ada.walks', avatarUrl: '/demo/avatars/avatar-19.png', avatarColor: '#8a644f' },
  { name: 'Joana Silva', handle: '@joana.volta', avatarUrl: '/demo/avatars/avatar-20.png', avatarColor: '#b45b52' },
];

const DEMO_STORIES = [
  {
    slug: 'marina-run-again',
    owner: 0,
    coverColor: '#d87932',
    category: 'body',
    moment: 'starting',
    totalDays: 45,
    currentDay: 12,
    streak: 4,
    progressPct: 27,
    title: { pt: 'Voltar a correr sem me punir', en: 'Run again without punishing myself' },
    goal: { pt: 'Quero recuperar o gosto pela corrida, sem transformar isso em cobrança.', en: 'I want to enjoy running again without turning it into self-pressure.' },
    updates: [
      { day: 1, kind: 'step', pt: 'Calcei o tenis e caminhei 15 minutos. Era so isso por hoje.', en: 'I put my shoes on and walked for 15 minutes. That was enough for today.' },
      { day: 8, kind: 'setback', pt: 'A semana apertou e nao fui. Em vez de sumir, voltei para uma volta curta.', en: 'The week got heavy and I missed it. Instead of disappearing, I came back for a short lap.' },
      { day: 12, kind: 'win', pt: 'Corri 12 minutos seguidos e terminei com vontade de voltar amanha.', en: 'I ran 12 minutes straight and finished wanting to come back tomorrow.' },
    ],
  },
  {
    slug: 'clara-english-everyday',
    owner: 1,
    coverColor: '#bd5b52',
    category: 'work',
    moment: 'building',
    totalDays: 60,
    currentDay: 18,
    streak: 9,
    progressPct: 30,
    title: { pt: '20 minutos de ingles por dia', en: '20 minutes of English a day' },
    goal: { pt: 'Preciso soltar o ingles para entrevistas e viagens, sem depender de picos de motivacao.', en: 'I need to loosen up my English for interviews and travel, without depending on motivation spikes.' },
    updates: [
      { day: 2, kind: 'step', pt: 'Ouvi um podcast curto e repeti frases em voz alta no carro.', en: 'I played a short podcast and repeated phrases out loud in the car.' },
      { day: 11, kind: 'learned', pt: 'Percebi que estudar pouco todo dia funciona melhor do que maratona no domingo.', en: 'I realized a small daily study block works better than a Sunday marathon.' },
      { day: 18, kind: 'win', pt: 'Consegui me apresentar em ingles sem travar tanto. Pequena vitoria.', en: 'I introduced myself in English without freezing so much. Small win.' },
    ],
  },
  {
    slug: 'kenji-sleep-routine',
    owner: 2,
    coverColor: '#4f6b8a',
    category: 'life',
    moment: 'health',
    totalDays: 30,
    currentDay: 9,
    streak: 3,
    progressPct: 30,
    title: { pt: 'Dormir melhor de verdade', en: 'Actually sleep better' },
    goal: { pt: 'Quero sair do ciclo de tela ate tarde e acordar menos quebrado.', en: 'I want to break the late-night screen loop and wake up less wrecked.' },
    updates: [
      { day: 1, kind: 'step', pt: 'Deixei o celular fora da cama e li duas paginas antes de dormir.', en: 'I kept my phone away from the bed and read two pages before sleep.' },
      { day: 6, kind: 'setback', pt: 'Voltei a rolar tela ate tarde, mas hoje reiniciei o ritual sem drama.', en: 'I went back to doomscrolling late, but today I restarted the ritual without drama.' },
      { day: 9, kind: 'win', pt: 'Acordei antes do alarme pela primeira vez em semanas.', en: 'I woke up before the alarm for the first time in weeks.' },
    ],
  },
  {
    slug: 'lina-money-reset',
    owner: 3,
    coverColor: '#687d5f',
    category: 'life',
    moment: 'rebuilding',
    totalDays: 50,
    currentDay: 16,
    streak: 5,
    progressPct: 32,
    title: { pt: 'Reorganizar minha vida financeira', en: 'Reset my finances' },
    goal: { pt: 'Quero parar de fugir do extrato e montar uma rotina simples para o dinheiro.', en: 'I want to stop avoiding my bank app and create a simple money routine.' },
    updates: [
      { day: 1, kind: 'step', pt: 'Abri a planilha e listei tudo sem tentar consertar nada ainda.', en: 'I opened the spreadsheet and listed everything without trying to fix it yet.' },
      { day: 10, kind: 'learned', pt: 'Separar gastos fixos dos impulsos deixou o problema bem mais claro.', en: 'Separating fixed costs from impulse spending made the problem much clearer.' },
      { day: 16, kind: 'win', pt: 'Fechei a semana sem comprar por ansiedade. Isso ja muda o jogo.', en: 'I finished the week without buying out of anxiety. That already changes the game.' },
    ],
  },
  {
    slug: 'paulo-portfolio-freelance',
    owner: 4,
    coverColor: '#5d6c57',
    category: 'work',
    moment: 'courage',
    totalDays: 40,
    currentDay: 14,
    streak: 6,
    progressPct: 35,
    title: { pt: 'Montar meu portfolio e me expor', en: 'Build my portfolio and put it out there' },
    goal: { pt: 'Preciso organizar meus trabalhos e parar de esperar “ficar perfeito” para publicar.', en: 'I need to organize my work and stop waiting for perfect before posting.' },
    updates: [
      { day: 3, kind: 'step', pt: 'Escolhi tres projetos e escrevi um rascunho honesto sobre cada um.', en: 'I picked three projects and wrote an honest draft about each one.' },
      { day: 9, kind: 'setback', pt: 'Travei antes de publicar. Hoje so ajustei a capa e deixei pronto.', en: 'I froze before publishing. Today I only adjusted the cover and left it ready.' },
      { day: 14, kind: 'win', pt: 'Publiquei a primeira pagina. Foi menos assustador do que eu imaginava.', en: 'I published the first page. It was less scary than I imagined.' },
    ],
  },
  {
    slug: 'zuri-draw-daily',
    owner: 5,
    coverColor: '#4a7d91',
    category: 'art',
    moment: 'rebuilding',
    totalDays: 30,
    currentDay: 21,
    streak: 11,
    progressPct: 70,
    title: { pt: 'Desenhar de novo, sem pressa', en: 'Draw again, slowly' },
    goal: { pt: 'Quero voltar a criar sem transformar desenho em prova de valor pessoal.', en: 'I want to create again without turning drawing into a test of personal worth.' },
    updates: [
      { day: 1, kind: 'step', pt: 'Fiz um desenho de 10 minutos sem apagar nada.', en: 'I made a 10-minute drawing without erasing anything.' },
      { day: 13, kind: 'learned', pt: 'Quando o tempo e curto eu desenho mais leve, e isso tem sido bom.', en: 'When time is short I draw more lightly, and that has been good.' },
      { day: 21, kind: 'win', pt: 'Completei minha terceira pagina seguida. Estou sentindo minha mao voltar.', en: 'I completed my third full page in a row. I can feel my hand coming back.' },
    ],
  },
  {
    slug: 'nick-no-alcohol-30',
    owner: 6,
    coverColor: '#866a52',
    category: 'body',
    moment: 'health',
    totalDays: 30,
    currentDay: 7,
    streak: 2,
    progressPct: 23,
    title: { pt: '30 dias sem alcool', en: '30 days without alcohol' },
    goal: { pt: 'Quero entender meu corpo e meu humor sem usar bebida como piloto automatico.', en: 'I want to understand my body and mood without using drinking as autopilot.' },
    updates: [
      { day: 1, kind: 'step', pt: 'Troquei a cerveja da noite por agua com gelo e limao. Parece simples, mas foi estranho.', en: 'I swapped my night beer for iced lemon water. Sounds simple, but it felt strange.' },
      { day: 5, kind: 'setback', pt: 'Sai com amigos e bebi. Em vez de desistir, comecei o dia 1 de novo hoje.', en: 'I went out with friends and drank. Instead of quitting, I started day 1 again today.' },
      { day: 7, kind: 'win', pt: 'Dois dias seguidos limpo e dormindo melhor. Vou proteger esse ritmo.', en: 'Two clean days in a row and sleeping better. I want to protect this rhythm.' },
    ],
  },
  {
    slug: 'helena-therapy-journal',
    owner: 7,
    coverColor: '#9a7b5d',
    category: 'life',
    moment: 'hardphase',
    totalDays: 90,
    currentDay: 24,
    streak: 7,
    progressPct: 26,
    title: { pt: 'Escrever depois da terapia', en: 'Write after therapy' },
    goal: { pt: 'Quero registrar o que estou entendendo sobre mim, sem deixar tudo evaporar.', en: 'I want to keep track of what I am understanding about myself instead of letting it evaporate.' },
    updates: [
      { day: 4, kind: 'step', pt: 'Escrevi tres linhas sobre o que senti, nao sobre o que “deveria” sentir.', en: 'I wrote three lines about what I felt, not what I “should” feel.' },
      { day: 18, kind: 'learned', pt: 'Quando eu nomeio a emocao, ela pesa menos no corpo.', en: 'When I name the emotion, it weighs less in my body.' },
      { day: 24, kind: 'win', pt: 'Hoje reli uma entrada antiga e percebi que ja nao estou no mesmo lugar.', en: 'Today I reread an older entry and realized I am not in the same place anymore.' },
    ],
  },
  {
    slug: 'mei-declutter-room',
    owner: 8,
    coverColor: '#7b8f87',
    category: 'home',
    moment: 'building',
    totalDays: 21,
    currentDay: 6,
    streak: 6,
    progressPct: 29,
    title: { pt: 'Arrumar meu quarto por partes', en: 'Declutter my room in parts' },
    goal: { pt: 'Quero tirar a sensacao de caos do quarto sem esperar um sabado perfeito.', en: 'I want to remove the sense of chaos from my room without waiting for a perfect Saturday.' },
    updates: [
      { day: 1, kind: 'step', pt: 'Separei uma gaveta. So uma. Ja ficou mais leve.', en: 'I sorted one drawer. Just one. It already felt lighter.' },
      { day: 4, kind: 'win', pt: 'Montei uma caixa de doacao e consegui fechar. Isso nunca era facil.', en: 'I put together a donation box and actually closed it. That was never easy.' },
      { day: 6, kind: 'learned', pt: 'Dez minutos por dia estao funcionando melhor do que faxina de exaustao.', en: 'Ten minutes a day is working better than all-out exhausting cleaning.' },
    ],
  },
  {
    slug: 'diego-job-search',
    owner: 9,
    coverColor: '#c57a43',
    category: 'work',
    moment: 'starting',
    totalDays: 45,
    currentDay: 11,
    streak: 4,
    progressPct: 24,
    title: { pt: 'Buscar trabalho sem me desmontar', en: 'Job searching without falling apart' },
    goal: { pt: 'Quero criar um ritmo sustentavel para candidaturas, em vez de tudo ou nada.', en: 'I want a sustainable application rhythm instead of all or nothing.' },
    updates: [
      { day: 2, kind: 'step', pt: 'Atualizei meu curriculo e mandei duas candidaturas com calma.', en: 'I updated my resume and sent two applications carefully.' },
      { day: 7, kind: 'setback', pt: 'Recebi um nao e fiquei mal. Hoje so revisei uma vaga e mantive o plano vivo.', en: 'I got a rejection and felt awful. Today I only reviewed one role and kept the plan alive.' },
      { day: 11, kind: 'win', pt: 'Marquei uma conversa inicial para semana que vem. Ja valeu ter continuado.', en: 'I booked an intro call for next week. Continuing was worth it already.' },
    ],
  },
  {
    slug: 'laura-cook-at-home',
    owner: 10,
    coverColor: '#6f8365',
    category: 'home',
    moment: 'building',
    totalDays: 30,
    currentDay: 17,
    streak: 8,
    progressPct: 57,
    title: { pt: 'Cozinhar em casa mais vezes', en: 'Cook at home more often' },
    goal: { pt: 'Quero comer melhor e gastar menos, mas sem transformar a cozinha em peso.', en: 'I want to eat better and spend less without turning the kitchen into a burden.' },
    updates: [
      { day: 3, kind: 'step', pt: 'Preparei arroz, legumes e frango para dois dias. Nada sofisticado, so funcional.', en: 'I made rice, vegetables and chicken for two days. Nothing fancy, just useful.' },
      { day: 9, kind: 'learned', pt: 'Se deixo a pia organizada antes, eu volto a cozinhar mais facil.', en: 'If I leave the sink organized first, I come back to cooking more easily.' },
      { day: 17, kind: 'win', pt: 'Passei a semana inteira sem pedir delivery no impulso.', en: 'I made it through the whole week without impulse takeout.' },
    ],
  },
  {
    slug: 'omar-read-25-pages',
    owner: 11,
    coverColor: '#506d8a',
    category: 'life',
    moment: 'rebuilding',
    totalDays: 40,
    currentDay: 22,
    streak: 12,
    progressPct: 55,
    title: { pt: 'Ler 25 paginas por noite', en: 'Read 25 pages at night' },
    goal: { pt: 'Quero voltar a ter leitura como descanso, nao como meta performatica.', en: 'I want reading back as rest, not as a performative goal.' },
    updates: [
      { day: 1, kind: 'step', pt: 'Li 12 paginas e parei no meio de um capitulo sem culpa.', en: 'I read 12 pages and stopped mid-chapter without guilt.' },
      { day: 15, kind: 'win', pt: 'Terminei meu primeiro livro no ano. Demorou, mas voltou.', en: 'I finished my first book of the year. It took time, but it came back.' },
      { day: 22, kind: 'learned', pt: 'Quando leio cedo demais eu durmo melhor. Virou parte do fechamento do dia.', en: 'When I read early enough I sleep better. It became part of closing the day.' },
    ],
  },
  {
    slug: 'sofia-digital-detox',
    owner: 12,
    coverColor: '#c26a4a',
    category: 'life',
    moment: 'health',
    totalDays: 21,
    currentDay: 5,
    streak: 1,
    progressPct: 24,
    title: { pt: 'Menos tela no fim do dia', en: 'Less screen time at night' },
    goal: { pt: 'Quero tirar o celular do centro da noite e recuperar um pouco de silencio.', en: 'I want to remove my phone from the center of the night and get some silence back.' },
    updates: [
      { day: 1, kind: 'step', pt: 'Ativei limite em dois apps e deixei o carregador longe da cama.', en: 'I set limits on two apps and left the charger away from the bed.' },
      { day: 4, kind: 'setback', pt: 'Ontem caí no loop de videos. Hoje retomei sem me xingar.', en: 'Yesterday I fell into the video loop. Today I restarted without attacking myself.' },
      { day: 5, kind: 'win', pt: 'Jantei sem tocar no celular. Pode parecer pouco, mas mudou meu humor.', en: 'I had dinner without touching my phone. It may sound small, but it changed my mood.' },
    ],
  },
  {
    slug: 'yuri-guitar-night',
    owner: 13,
    coverColor: '#60748c',
    category: 'art',
    moment: 'courage',
    totalDays: 30,
    currentDay: 13,
    streak: 5,
    progressPct: 43,
    title: { pt: 'Voltar para o violao a noite', en: 'Return to guitar at night' },
    goal: { pt: 'Quero reconectar com musica de um jeito simples, sem obrigacao de evoluir rapido.', en: 'I want to reconnect with music in a simple way, without pressure to improve fast.' },
    updates: [
      { day: 2, kind: 'step', pt: 'Afinei o violao e toquei duas musicas antigas, mesmo errando.', en: 'I tuned the guitar and played two old songs, mistakes included.' },
      { day: 8, kind: 'learned', pt: 'Cinco minutos funcionam melhor do que esperar uma hora livre.', en: 'Five minutes works better than waiting for a free hour.' },
      { day: 13, kind: 'win', pt: 'Gravei um trechinho para mim mesmo. Fazia anos que eu nao fazia isso.', en: 'I recorded a small clip for myself. I had not done that in years.' },
    ],
  },
  {
    slug: 'amira-back-to-gym',
    owner: 14,
    coverColor: '#c88054',
    category: 'body',
    moment: 'notgiveup',
    totalDays: 50,
    currentDay: 19,
    streak: 6,
    progressPct: 38,
    title: { pt: 'Voltar para a academia com gentileza', en: 'Return to the gym gently' },
    goal: { pt: 'Quero recuperar forca sem repetir o ciclo de exagero, culpa e sumico.', en: 'I want strength back without repeating the cycle of overdoing it, guilt and disappearing.' },
    updates: [
      { day: 1, kind: 'step', pt: 'Fui so para caminhar e alongar. Ja foi uma vitoria aparecer.', en: 'I went just to walk and stretch. Showing up was already a win.' },
      { day: 12, kind: 'setback', pt: 'Fiquei tres dias sem ir. Hoje fiz meia hora e aceitei isso como retorno.', en: 'I skipped three days. Today I did half an hour and accepted that as a comeback.' },
      { day: 19, kind: 'win', pt: 'Sai com energia em vez de culpa. Esse era o objetivo desde o inicio.', en: 'I left with energy instead of guilt. That was the real goal from the start.' },
    ],
  },
  {
    slug: 'leo-small-business',
    owner: 15,
    coverColor: '#728f7a',
    category: 'work',
    moment: 'building',
    totalDays: 100,
    currentDay: 31,
    streak: 10,
    progressPct: 31,
    title: { pt: 'Tirar meu negocio do papel', en: 'Bring my small business to life' },
    goal: { pt: 'Quero construir algo meu sem romantizar cansaco, com passos pequenos e reais.', en: 'I want to build something of my own without romanticizing exhaustion, through small real steps.' },
    updates: [
      { day: 5, kind: 'step', pt: 'Defini oferta, nome e primeira pagina. Ainda simples, mas agora existe.', en: 'I defined the offer, name and first page. Still simple, but now it exists.' },
      { day: 18, kind: 'learned', pt: 'Quando eu testo rapido, eu travo menos do que quando tento prever tudo.', en: 'When I test quickly, I freeze less than when I try to predict everything.' },
      { day: 31, kind: 'win', pt: 'Recebi meu primeiro pagamento pequeno. Nao e sobre o valor, e sobre o sinal.', en: 'I received my first small payment. It is not about the amount, it is about the signal.' },
    ],
  },
  {
    slug: 'ines-heal-breakup',
    owner: 16,
    coverColor: '#866b60',
    category: 'life',
    moment: 'hardphase',
    totalDays: 60,
    currentDay: 27,
    streak: 7,
    progressPct: 45,
    title: { pt: 'Me reconstruir depois do termino', en: 'Rebuild after the breakup' },
    goal: { pt: 'Nao quero acelerar a dor. Quero so voltar a morar em mim mesma, aos poucos.', en: 'I do not want to rush the pain. I just want to live inside myself again, slowly.' },
    updates: [
      { day: 3, kind: 'step', pt: 'Saí para tomar cafe sozinha. Foi estranho, mas importante.', en: 'I went out for coffee by myself. It felt strange, but important.' },
      { day: 14, kind: 'setback', pt: 'Hoje chorei muito. Ainda assim escrevi aqui para nao sumir de mim.', en: 'I cried a lot today. I still wrote here so I would not disappear from myself.' },
      { day: 27, kind: 'win', pt: 'Percebi que consegui passar o domingo sem esperar mensagem. Isso e novo.', en: 'I realized I got through Sunday without waiting for a text. That is new.' },
    ],
  },
  {
    slug: 'bruno-code-every-night',
    owner: 17,
    coverColor: '#b56644',
    category: 'work',
    moment: 'starting',
    totalDays: 90,
    currentDay: 15,
    streak: 8,
    progressPct: 17,
    title: { pt: 'Estudar codigo toda noite', en: 'Study code every night' },
    goal: { pt: 'Quero trocar de area sem depender de explosoes de energia que nunca duram.', en: 'I want to change careers without depending on energy explosions that never last.' },
    updates: [
      { day: 1, kind: 'step', pt: 'Separei 25 minutos e terminei um modulo que eu vinha adiando.', en: 'I set aside 25 minutes and finished a module I had been postponing.' },
      { day: 9, kind: 'learned', pt: 'Quando eu anoto o que entendi, lembro mais do que quando so assisto.', en: 'When I write what I understood, I retain more than when I only watch.' },
      { day: 15, kind: 'win', pt: 'Montei meu primeiro componente sozinho. Pequeno, mas meu.', en: 'I built my first component on my own. Small, but mine.' },
    ],
  },
  {
    slug: 'ada-morning-walk',
    owner: 18,
    coverColor: '#8a644f',
    category: 'body',
    moment: 'health',
    totalDays: 21,
    currentDay: 20,
    streak: 14,
    progressPct: 95,
    title: { pt: 'Caminhar antes do trabalho', en: 'Walk before work' },
    goal: { pt: 'Quero comecar o dia no meu corpo, e nao direto no computador.', en: 'I want to start the day in my body, not straight inside the computer.' },
    updates: [
      { day: 2, kind: 'step', pt: 'Desci quinze minutos antes e dei uma volta no quarteirao.', en: 'I left fifteen minutes earlier and walked around the block.' },
      { day: 12, kind: 'win', pt: 'Ja nao negocio tanto comigo. A caminhada virou parte da manha.', en: 'I do not negotiate with myself as much anymore. The walk became part of the morning.' },
      { day: 20, kind: 'learned', pt: 'Nao preciso de uma caminhada perfeita. Preciso so sair da porta.', en: 'I do not need a perfect walk. I just need to get out the door.' },
    ],
  },
  {
    slug: 'joana-selfcare-motherhood',
    owner: 19,
    coverColor: '#b45b52',
    category: 'life',
    moment: 'courage',
    totalDays: 30,
    currentDay: 10,
    streak: 4,
    progressPct: 33,
    title: { pt: 'Voltar a caber na minha propria rotina', en: 'Fit back into my own routine' },
    goal: { pt: 'Quero cuidar de mim sem culpa, mesmo em dias corridos e cheios.', en: 'I want to care for myself without guilt, even on packed busy days.' },
    updates: [
      { day: 1, kind: 'step', pt: 'Tomei cafe sentada e sem celular por dez minutos. Parecia luxo.', en: 'I had coffee sitting down without my phone for ten minutes. It felt like luxury.' },
      { day: 6, kind: 'setback', pt: 'A semana atropelou tudo. Hoje retomei com um banho demorado e silencio.', en: 'The week ran over everything. Today I came back with a long shower and silence.' },
      { day: 10, kind: 'win', pt: 'Consegui pedir ajuda e usar esse tempo para mim, sem justificar demais.', en: 'I managed to ask for help and use that time for myself, without overexplaining.' },
    ],
  },
];

function pickText(value, locale) {
  if (!value || typeof value !== 'object') return value;
  return locale === 'pt' ? value.pt : value.en;
}

function buildSummary(updates, locale) {
  const latest = updates[updates.length - 1];
  return latest ? latest.text : '';
}

export function buildDemoStories(locale = 'pt') {
  return DEMO_STORIES.map((story) => {
    const owner = DEMO_OWNERS[story.owner];
    const updates = story.updates.map((update, index) => ({
      id: `${story.slug}-day-${update.day}`,
      day_number: update.day,
      kind: update.kind,
      text: pickText(update, locale),
      photo_url: null,
      video_url: null,
      order: index,
    }));

    return {
      id: `demo-${story.slug}`,
      slug: story.slug,
      isDemo: true,
      title: pickText(story.title, locale),
      goal: pickText(story.goal, locale),
      preview: buildSummary(updates, locale),
      cover_color: story.coverColor,
      category: story.category,
      moment: story.moment,
      total_days: story.totalDays,
      owner,
      stats: {
        current_day: story.currentDay,
        streak: story.streak,
        progress_pct: story.progressPct,
        days_posted: updates.length,
      },
      updates,
    };
  });
}

export function getDemoStory(slug, locale = 'pt') {
  return buildDemoStories(locale).find((story) => story.slug === slug) || null;
}

export function buildDemoFeedItems(locale = 'pt') {
  return buildDemoStories(locale).map((story) => {
    const latest = story.updates[story.updates.length - 1];
    return {
      id: `feed-${story.slug}`,
      day_number: latest.day_number,
      kind: latest.kind,
      text: latest.text,
      photo_url: null,
      video_url: null,
      demo: true,
      encouraged: false,
      journey: {
        slug: story.slug,
        title: story.title,
        category: story.category,
      },
      owner: {
        ...story.owner,
        id: null,
        avatar_color: story.owner.avatarColor,
        avatar_url: story.owner.avatarUrl,
      },
    };
  });
}
