export const TOPICS = {
  'como-voltar-a-estudar': { by: 'category', val: 'study',
    pt: { h: 'Como voltar a estudar', d: 'Histórias reais de quem recomeçou os estudos — um dia de cada vez, sem culpa.' },
    en: { h: 'How to get back to studying', d: 'Real stories of people restarting their studies — one day at a time.' } },
  'como-comecar-a-treinar': { by: 'category', val: 'body',
    pt: { h: 'Como começar a treinar', d: 'Pessoas comuns dando o primeiro passo no corpo e voltando no dia seguinte.' },
    en: { h: 'How to start working out', d: 'Ordinary people taking the first step and coming back the next day.' } },
  'como-cuidar-da-saude-mental': { by: 'category', val: 'mind',
    pt: { h: 'Como cuidar da saúde mental', d: 'Recomeços de autocuidado, no seu ritmo. Não é terapia — é continuar.' },
    en: { h: 'How to care for your mental health', d: 'Self-care restarts at your own pace. Not therapy — just continuing.' } },
  'como-reconstruir-minha-rotina': { by: 'moment', val: 'rebuilding',
    pt: { h: 'Como reconstruir minha rotina', d: 'Quem está reconstruindo a vida depois de uma virada, passo a passo.' },
    en: { h: 'How to rebuild my routine', d: 'People rebuilding life after a turning point, step by step.' } },
  'como-comecar-um-negocio': { by: 'category', val: 'work',
    pt: { h: 'Como começar um negócio', d: 'Primeiros passos de quem está construindo algo do zero, publicamente.' },
    en: { h: 'How to start a business', d: 'First steps of people building something from scratch, in public.' } },
  'como-criar-um-habito': { by: 'category', val: 'habit',
    pt: { h: 'Como criar um hábito', d: 'Pequenos passos diários que viram consistência. Recaída não zera tudo.' },
    en: { h: 'How to build a habit', d: 'Small daily steps that become consistency. A slip doesn’t reset it all.' } },
};
export const TOPIC_SLUGS = Object.keys(TOPICS);
