'use client';
import { useEffect, useState } from 'react';

export default function MessageClient({ labels }) {
  const [conversations, setConversations] = useState([]); const [query, setQuery] = useState(''); const [results, setResults] = useState([]); const [selected, setSelected] = useState(null); const [messages, setMessages] = useState([]); const [text, setText] = useState(''); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  useEffect(() => { fetch('/api/messages').then(r => r.json()).then(d => setConversations(d.conversations || [])).catch(() => {}); const target = new URLSearchParams(window.location.search).get('para'); if (target) { fetch(`/api/profiles?q=${encodeURIComponent(target)}`).then(r => r.json()).then(d => { if (d.profiles?.[0]) openConversation(d.profiles[0]); }).catch(() => {}); } }, []);
  useEffect(() => { if (query.trim().length < 2) { setResults([]); return; } const timer = setTimeout(() => fetch(`/api/profiles?q=${encodeURIComponent(query.trim())}`).then(r => r.json()).then(d => setResults(d.profiles || [])).catch(() => {}), 250); return () => clearTimeout(timer); }, [query]);
  async function openConversation(person) { setSelected(person); setQuery(''); setResults([]); setNotice(''); const r = await fetch(`/api/messages?with=${encodeURIComponent(person.id)}`); const d = await r.json().catch(() => ({})); if (!r.ok) setNotice(labels.connection); else setMessages(d.messages || []); }
  async function send(e) { e.preventDefault(); if (!text.trim() || busy || !selected) return; setBusy(true); setNotice(''); const r = await fetch('/api/messages', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ recipientId: selected.id, text }) }); const d = await r.json().catch(() => ({})); if (r.status === 422) setNotice(labels.unsafe); else if (!r.ok) setNotice(labels.error); else { setMessages(items => [...items, d.message]); setText(''); } setBusy(false); }
  const personRow = p => <button key={p.id} type="button" onClick={() => openConversation(p)}><span className="message-avatar" style={{ background: p.avatar_color || 'var(--orange)' }}>{p.avatar_url ? <img src={p.avatar_url} alt="" /> : (p.name || '?')[0]}</span><span><b>{p.name}</b><small>{p.handle}</small></span></button>;
  return <section className="messages-shell"><div className="messages-head"><div><span className="eyebrow">{labels.eyebrow}</span><h1>{labels.title}</h1></div><a className="ghost-btn" href="/home">{labels.back}</a></div><div className="message-search"><input value={query} onChange={e => setQuery(e.target.value)} placeholder={labels.search} />{results.length > 0 && <div className="message-results">{results.map(personRow)}</div>}</div><div className="messages-grid"><aside className="conversation-list">{conversations.length ? conversations.map(c => <button type="button" className={selected?.id === c.person.id ? 'selected' : ''} key={c.person.id} onClick={() => openConversation(c.person)}><span className="message-avatar" style={{ background: c.person.avatar_color || 'var(--orange)' }}>{c.person.avatar_url ? <img src={c.person.avatar_url} alt="" /> : (c.person.name || '?')[0]}</span><span><b>{c.person.name}</b><small>{c.body}</small></span></button>) : <p className="message-muted">{labels.empty}</p>}</aside><div className="message-thread">{selected ? <><div className="thread-head"><b>{selected.name}</b><a href={`/${selected.handle}`}>{selected.handle}</a></div><div className="thread-body">{messages.length ? messages.map(m => <p className={m.sender_id === selected.id ? 'received' : 'sent'} key={m.id}>{m.body}</p>) : <p className="message-muted">{labels.start}</p>}</div><form className="message-form" onSubmit={send}><input value={text} onChange={e => setText(e.target.value)} maxLength={1000} placeholder={labels.placeholder} /><button disabled={busy || !text.trim()}>{busy ? labels.sending : labels.send}</button></form></> : <p className="message-muted">{labels.choose}</p>}{notice && <p className="message-notice">{notice}</p>}</div></div></section>;
}
